id: I69846A66
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:11:04+00:00'
last_modified: '2022-06-10T06:15:24.092897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN53
  title: སྔ་འགྱུར་བཀའ་མའི་ཡིག་རྙིང་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    755C:
      image_group_id: I3CN60
      title: Volume 1 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 903
      order: 1
      base_file: 755C.txt
    4B66:
      image_group_id: I3CN61
      title: Volume 2 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 574
      order: 2
      base_file: 4B66.txt
    E514:
      image_group_id: I3CN62
      title: Volume 3 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 834
      order: 3
      base_file: E514.txt
    63C6:
      image_group_id: I3CN63
      title: Volume 4 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 705
      order: 4
      base_file: 63C6.txt
    88AD:
      image_group_id: I3CN64
      title: Volume 5 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 732
      order: 5
      base_file: 88AD.txt
    E47A:
      image_group_id: I3CN65
      title: Volume 6 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 328
      order: 6
      base_file: E47A.txt
    4B1E:
      image_group_id: I3CN66
      title: Volume 7 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 293
      order: 7
      base_file: 4B1E.txt
    '9694':
      image_group_id: I3CN67
      title: Volume 8 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 579
      order: 8
      base_file: 9694.txt
    09B3:
      image_group_id: I3CN68
      title: Volume 9 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 729
      order: 9
      base_file: 09B3.txt
    1D40:
      image_group_id: I3CN69
      title: Volume 10 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 484
      order: 10
      base_file: 1D40.txt
    FAB9:
      image_group_id: I3CN70
      title: Volume 11 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 820
      order: 11
      base_file: FAB9.txt
    9FEC:
      image_group_id: I3CN71
      title: Volume 12 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 611
      order: 12
      base_file: 9FEC.txt
    '8391':
      image_group_id: I3CN72
      title: Volume 13 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 427
      order: 13
      base_file: 8391.txt
    C963:
      image_group_id: I3CN73
      title: Volume 14 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 424
      order: 14
      base_file: C963.txt
    546B:
      image_group_id: I3CN74
      title: Volume 15 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 889
      order: 15
      base_file: 546B.txt
    0F8F:
      image_group_id: I3CN75
      title: Volume 16 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 576
      order: 16
      base_file: 0F8F.txt
    823E:
      image_group_id: I3CN76
      title: Volume 17 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 276
      order: 17
      base_file: 823E.txt
    '2189':
      image_group_id: I3CN77
      title: Volume 18 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 252
      order: 18
      base_file: 2189.txt
    FFE2:
      image_group_id: I3CN78
      title: Volume 19 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 843
      order: 19
      base_file: FFE2.txt
    '1660':
      image_group_id: I3CN79
      title: Volume 20 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 304
      order: 20
      base_file: 1660.txt
    F16A:
      image_group_id: I3CN80
      title: Volume 21 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 608
      order: 21
      base_file: F16A.txt
    B005:
      image_group_id: I3CN81
      title: Volume 22 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 453
      order: 22
      base_file: B005.txt
    '1968':
      image_group_id: I3CN82
      title: Volume 23 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 523
      order: 23
      base_file: 1968.txt
    '6562':
      image_group_id: I3CN83
      title: Volume 24 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 700
      order: 24
      base_file: 6562.txt
    D6B5:
      image_group_id: I3CN84
      title: Volume 25 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 474
      order: 25
      base_file: D6B5.txt
    D014:
      image_group_id: I3CN85
      title: Volume 26 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 541
      order: 26
      base_file: D014.txt
    '7731':
      image_group_id: I3CN86
      title: Volume 27 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 574
      order: 27
      base_file: 7731.txt
    D010:
      image_group_id: I3CN87
      title: Volume 28 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 750
      order: 28
      base_file: D010.txt
    '8786':
      image_group_id: I3CN88
      title: Volume 29 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 503
      order: 29
      base_file: 8786.txt
    68E1:
      image_group_id: I3CN89
      title: Volume 30 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 667
      order: 30
      base_file: 68E1.txt
    11CE:
      image_group_id: I3CN90
      title: Volume 31 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 338
      order: 31
      base_file: 11CE.txt
    D44A:
      image_group_id: I3CN91
      title: Volume 32 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 418
      order: 32
      base_file: D44A.txt
    7C49:
      image_group_id: I3CN92
      title: Volume 33 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 511
      order: 33
      base_file: 7C49.txt
    A284:
      image_group_id: I3CN93
      title: Volume 34 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 92
      order: 34
      base_file: A284.txt
    51D3:
      image_group_id: I3CN94
      title: Volume 35 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 817
      order: 35
      base_file: 51D3.txt
    '8528':
      image_group_id: I3CN95
      title: Volume 36 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 586
      order: 36
      base_file: 8528.txt
    43BC:
      image_group_id: I3CN96
      title: Volume 37 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 338
      order: 37
      base_file: 43BC.txt
    C1CC:
      image_group_id: I3CN97
      title: Volume 38 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 484
      order: 38
      base_file: C1CC.txt
    '2715':
      image_group_id: I3CN98
      title: Volume 39 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 588
      order: 39
      base_file: 2715.txt
    D49F:
      image_group_id: I3CN99
      title: Volume 40 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 196
      order: 40
      base_file: D49F.txt
    8E03:
      image_group_id: I3CN100
      title: Volume 41 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 642
      order: 41
      base_file: 8E03.txt
    CCE0:
      image_group_id: I3CN101
      title: Volume 42 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 411
      order: 42
      base_file: CCE0.txt
    '8923':
      image_group_id: I3CN102
      title: Volume 43 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 434
      order: 43
      base_file: 8923.txt
    2F7E:
      image_group_id: I3CN103
      title: Volume 44 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 566
      order: 44
      base_file: 2F7E.txt
    A799:
      image_group_id: I3CN104
      title: Volume 45 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 460
      order: 45
      base_file: A799.txt
    '6272':
      image_group_id: I3CN105
      title: Volume 46 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 696
      order: 46
      base_file: 6272.txt
    '8375':
      image_group_id: I3CN106
      title: Volume 47 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 1423
      order: 47
      base_file: 8375.txt
    '6648':
      image_group_id: I3CN107
      title: Volume 48 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 1140
      order: 48
      base_file: 6648.txt
    EB17:
      image_group_id: I3CN108
      title: Volume 49 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 560
      order: 49
      base_file: EB17.txt
    '5913':
      image_group_id: I3CN109
      title: Volume 50 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 404
      order: 50
      base_file: 5913.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
